openapi: "3.0.0"
info : 
  title : Api 연습
  description : 연습
  version : 1.0.0
servers : 
  - url : localhost:5005
paths:
  $ref: "./paths/index.yaml"
securityDefinitions: 
  apiKeyAuth :
    type: apiKey,
    in: header,
    name: authorizations,
    description: '토큰 값을 넣어주세요!'
components:
  parameters:
    file:
      name : file,
      in: formData,
      required: false,
      description : 첨부파일,
      schema : 
        type: 'file'
      
  